[custom.all.scgi]
type   = "local"
path   = "."
ipkg   = "scgi.ipkg"

[custom.all.scgi-example]
type   = "local"
path   = "example"
ipkg   = "scgi-example.ipkg"

[custom.all]
async.commit           = "latest:main"
async-posix.commit     = "latest:main"
ilex.commit            = "latest:main"
ilex-core.commit       = "latest:main"
ilex-json.commit       = "latest:main"
http-types.commit      = "latest:main"
http-server-api.commit = "latest:main"
