---
name: Lint

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - master

permissions: {}

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CLANG_FORMAT: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GENERATED_FILES: true
